services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:z
      - /app/node_modules

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app:z
      - /app/node_modules
    environment:
      - FRONTEND_URL=http://localhost:5173
      - DATABASE_URL=${DATABASE_URL}

  db:
    image: docker.io/library/postgres:16-alpine  # image officielle, rien à construire
    environment:                        # Postgres lit ces variables au démarrage
      POSTGRES_USER: ${POSTGRES_USER}   # ${...} = "va chercher dans le .env"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}       # crée automatiquement une base vide de ce nom
    ports:
      - "5432:5432"                     # Le port sur lequel Postgres ecoute. pour t'y connecter depuis TA machine
    volumes:
      - pgdata:/var/lib/postgresql/data # où Postgres range ses données

volumes:
  pgdata:                               # déclaration du volume nommé